### ISSUE TITLE
Can't reproduce results

### ISSUE THREAD

**Issue by Pizzawookiee** [fabio-sim/Depth-Anything-ONNX#17]
Testing with both the Dynamo script and a self-written one from the documentation but I consistently get this error when attempting the dynamo export:

torch.onnx.OnnxExporterError: Failed to export the model to ONNX. Generating SARIF report at 'report_dynamo_export.sarif'. SARIF is a standard format for the output of static analysis tools. SARIF logs can be loaded in VS Code SARIF viewer extension, or SARIF web viewer (https://microsoft.github.io/sarif-web-component/). Please report a bug on PyTorch Github: https://github.com/pytorch/pytorch/issues

The sarif file in question is 1kb and registers as empty in the web viewer.

In the error message I find this line: torch._dynamo.exc.Unsupported: 'inline in skipfiles: FloatFunctional.add | add 

I don't know what this line refers to or how to fix it.

**Comment by fabio-sim** [comment]
Hi @Pizzawookiee, thank you for your interest in Depth Anything ONNX.

Yeah, dynamo exporter is still in early stages, so it could probably be due to things like torch version etc. I was able to export in torch==2.3.1, but can't guarantee it works the same on other systems. There's probably some ways to go until it's fully stable
